### ISSUE TITLE
Create goals fragment and the input section for new goal

### ISSUE THREAD

**Issue by lima1756** [FBU2018-L3/1-Up#51] opened 2018-07-24 16:40 UTC

**Comment by lucieleblanc** [comment] 2018-07-25 22:18
This turned out to be duplicate of #57 because of the strategy I chose, but here is the [result](https://github.com/FBU2018-L3/1-Up/commit/08223ce9413685999995189da118325f2768965a)

**Closed as completed by lucieleblanc** 2018-07-25 22:18 UTC
Labels: enhancement, sprint3
